-- Phase 1 / Slice 3 — Class arms, subjects, class-subjects.
-- DDL generated by `prisma migrate diff --from-url <DIRECT_URL>
-- --to-schema-datamodel prisma/schema.prisma --script`; RLS policy block
-- appended verbatim from packages/db/prisma/policies/phase-1.sql (the
-- policy file is the source of truth — keep these in sync).

-- CreateEnum
CREATE TYPE "SubjectCategory" AS ENUM ('CORE', 'ELECTIVE', 'VOCATIONAL');

-- CreateTable
CREATE TABLE "class_arms" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "class_level_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "capacity" INTEGER,
    "class_teacher_id" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "class_arms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subjects" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "category" "SubjectCategory" NOT NULL DEFAULT 'CORE',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "subjects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "class_subjects" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "class_level_id" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "is_core" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "class_subjects_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "class_arms_school_id_idx" ON "class_arms"("school_id");

-- CreateIndex
CREATE INDEX "class_arms_class_teacher_id_idx" ON "class_arms"("class_teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "class_arms_school_id_class_level_id_code_key" ON "class_arms"("school_id", "class_level_id", "code");

-- CreateIndex
CREATE INDEX "subjects_school_id_idx" ON "subjects"("school_id");

-- CreateIndex
CREATE UNIQUE INDEX "subjects_school_id_code_key" ON "subjects"("school_id", "code");

-- CreateIndex
CREATE INDEX "class_subjects_school_id_idx" ON "class_subjects"("school_id");

-- CreateIndex
CREATE INDEX "class_subjects_subject_id_idx" ON "class_subjects"("subject_id");

-- CreateIndex
CREATE UNIQUE INDEX "class_subjects_school_id_class_level_id_subject_id_key" ON "class_subjects"("school_id", "class_level_id", "subject_id");

-- AddForeignKey
ALTER TABLE "class_arms" ADD CONSTRAINT "class_arms_class_level_id_fkey" FOREIGN KEY ("class_level_id") REFERENCES "class_levels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_arms" ADD CONSTRAINT "class_arms_class_teacher_id_fkey" FOREIGN KEY ("class_teacher_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_subjects" ADD CONSTRAINT "class_subjects_class_level_id_fkey" FOREIGN KEY ("class_level_id") REFERENCES "class_levels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_subjects" ADD CONSTRAINT "class_subjects_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 3 RLS policies (verbatim from prisma/policies/phase-1.sql).
-- All three tables follow the slice 1+2 shape: ENABLE + FORCE on the
-- table, then a tenant_isolation policy with USING + WITH CHECK on the
-- denormalised school_id column. class_subjects is an explicit join
-- (ClassLevel × Subject) with its own school_id — matches the documented
-- pattern for student_guardians/mastery_records/ai_interaction_logs
-- (cheap direct-check; defence-in-depth against a buggy controller).
-- ---------------------------------------------------------------------

ALTER TABLE class_arms     ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_arms     FORCE  ROW LEVEL SECURITY;
ALTER TABLE subjects       ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects       FORCE  ROW LEVEL SECURITY;
ALTER TABLE class_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_subjects FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON class_arms
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON subjects
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON class_subjects
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
