-- Phase 1 / Slice 11 — TeacherAssignment.
--
-- DDL generated by `prisma migrate diff --from-url $DIRECT_URL
-- --to-schema-datamodel ./prisma/schema.prisma --script` (live DB was at
-- the slice-10 migrated state). RLS policy block appended verbatim from
-- packages/db/prisma/policies/phase-1.sql (the policy file is the source
-- of truth — keep these in sync).
--
-- TeacherAssignment records "teacher T teaches subject S in class arm A for
-- year Y (optionally term-specific)". It is the data behind the teacher-
-- scope filter that closes acceptance #9 (a teacher sees only their assigned
-- arms + subjects). All endpoints are admin-only and post-tenant; no
-- SECURITY DEFINER function is added. SECURITY DEFINER count stays at 4.
--
-- Shape notes (schema.prisma carries the full rationale):
--   - Direct FKs to class_arms + subjects (NOT through class_subjects): a
--     teacher teaches a specific ARM, not a whole LEVEL.
--   - academic_year_id scopes the assignment; term_id is OPTIONAL (NULL =
--     whole year, set = term-specific). onDelete SET NULL on term_id.
--   - The unique (school_id, teacher_id, class_arm_id, subject_id,
--     academic_year_id, term_id) only blocks the SAME teacher being assigned
--     twice to an identical tuple — co-teaching (different teachers, same
--     arm+subject+year+term) is intentionally allowed (Q2, 2026-05-31).
--     CAVEAT: Postgres treats NULL term_id as DISTINCT, so two identical
--     whole-year rows do NOT collide at the DB; the service pre-checks for
--     that case and returns 409 TEACHER_ALREADY_ASSIGNED (P2002 catch is the
--     non-null backstop).
--
-- No data backfill: this is a brand-new empty table. The minimal `teacher`
-- system role (slice-10 migration) ALREADY grants teacher-assignment.read,
-- so no role seed change is needed here; the full RBAC rollup stays slice 13.

-- CreateTable
CREATE TABLE "teacher_assignments" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "teacher_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "term_id" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "teacher_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "teacher_assignments_school_id_idx" ON "teacher_assignments"("school_id");

-- CreateIndex
CREATE INDEX "teacher_assignments_teacher_id_idx" ON "teacher_assignments"("teacher_id");

-- CreateIndex
CREATE INDEX "teacher_assignments_class_arm_id_idx" ON "teacher_assignments"("class_arm_id");

-- CreateIndex
CREATE INDEX "teacher_assignments_school_id_academic_year_id_idx" ON "teacher_assignments"("school_id", "academic_year_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_assignments_school_id_teacher_id_class_arm_id_subje_key" ON "teacher_assignments"("school_id", "teacher_id", "class_arm_id", "subject_id", "academic_year_id", "term_id");

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_class_arm_id_fkey" FOREIGN KEY ("class_arm_id") REFERENCES "class_arms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_assignments" ADD CONSTRAINT "teacher_assignments_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "terms"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 11 RLS policy (verbatim from prisma/policies/phase-1.sql).
-- Direct school_id column; FORCE so the migration role cannot bypass it.
-- ---------------------------------------------------------------------

ALTER TABLE "teacher_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teacher_assignments" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "teacher_assignments"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
