-- Phase 1 / Slice 2 — Class levels.
-- DDL generated by `prisma migrate diff`; RLS policy appended verbatim from
-- packages/db/prisma/policies/phase-1.sql (the policy file is the source of
-- truth — keep these in sync).

-- CreateEnum
CREATE TYPE "ClassStage" AS ENUM ('NURSERY', 'PRIMARY', 'JSS', 'SSS');

-- CreateTable
CREATE TABLE "class_levels" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "stage" "ClassStage" NOT NULL,
    "order_index" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "class_levels_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "class_levels_school_id_idx" ON "class_levels"("school_id");

-- CreateIndex
CREATE INDEX "class_levels_school_id_order_index_idx" ON "class_levels"("school_id", "order_index");

-- CreateIndex
CREATE UNIQUE INDEX "class_levels_school_id_code_key" ON "class_levels"("school_id", "code");

-- ---------------------------------------------------------------------
-- Slice 2 RLS policy (verbatim from prisma/policies/phase-1.sql).
-- Same shape as slice 1: ENABLE + FORCE on the table, then a
-- tenant_isolation policy with USING + WITH CHECK on school_id.
--
-- The seed-on-signup that populates the 14 default rows runs INSIDE the
-- existing signupOwner transaction using the same `tx` handle. The GUC
-- `app.current_school_id` is set earlier in that tx by
-- `set_config(..., true)`, so RLS WITH CHECK is satisfied without needing
-- withTenant (which would nest $transaction — Prisma does not nest).
-- See apps/api/src/modules/auth/auth.service.ts:signupOwner for the call site.
-- ---------------------------------------------------------------------

ALTER TABLE class_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_levels FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON class_levels
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
