-- Phase 2 / Slice 7 — Daily attendance (attendance_records).
--
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma --script`
-- (live DB at the Phase-2 slice-5 migrated state — slice 6 added no table).
-- RLS policy block appended verbatim from packages/db/prisma/policies/phase-2.sql.
--
-- Daily attendance is UNIVERSAL (no opt-in). One row per (student × date);
-- re-marking upserts on the (school_id, student_id, date) unique. Flat plain-FK
-- convention (no enforced relations) — same as the assessment tables. The
-- subject-period table (subject_attendance_records) is slice 8.
--
-- SECURITY DEFINER count stays at 4: every endpoint is post-auth, post-tenant
-- (withTenant). CLAUDE.md inventory unchanged.

-- CreateEnum
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED');

-- CreateTable
CREATE TABLE "attendance_records" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "status" "AttendanceStatus" NOT NULL,
    "note" TEXT,
    "marked_by" TEXT NOT NULL,
    "marked_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "attendance_records_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "attendance_records_school_id_idx" ON "attendance_records"("school_id");

-- CreateIndex
CREATE INDEX "attendance_records_school_id_class_arm_id_date_idx" ON "attendance_records"("school_id", "class_arm_id", "date");

-- CreateIndex
CREATE INDEX "attendance_records_school_id_term_id_idx" ON "attendance_records"("school_id", "term_id");

-- CreateIndex
CREATE UNIQUE INDEX "attendance_records_school_id_student_id_date_key" ON "attendance_records"("school_id", "student_id", "date");

-- ---------------------------------------------------------------------
-- Slice 7 RLS policy (verbatim from prisma/policies/phase-2.sql). Own
-- school_id → flat direct-column check. FORCE so the migration role cannot
-- bypass at runtime.
-- ---------------------------------------------------------------------

ALTER TABLE "attendance_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "attendance_records" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "attendance_records"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
