-- Phase 2 / Slice 8 — Subject-period attendance (opt-in).
--
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma --script`
-- (live DB at the Phase-2 slice-7 migrated state).
-- RLS policy block appended verbatim from packages/db/prisma/policies/phase-2.sql.
--
-- Two changes in one migration:
--   1. schools.subject_attendance_enabled — the per-school opt-in flag (default
--      false; existing schools get false automatically, no data migration).
--   2. subject_attendance_records — the period-level table. One row per
--      (student × subject × date × period); re-marking upserts on the
--      (school_id, student_id, subject_id, date, period) unique. Flat plain-FK
--      convention (no enforced relations) — same as the daily attendance table.
--      Reuses the AttendanceStatus enum (no new enum).
--
-- SECURITY DEFINER count stays at 4: every endpoint is post-auth, post-tenant
-- (withTenant). CLAUDE.md inventory unchanged.

-- AlterTable
ALTER TABLE "schools" ADD COLUMN     "subject_attendance_enabled" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "subject_attendance_records" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "period" INTEGER NOT NULL,
    "status" "AttendanceStatus" NOT NULL,
    "note" TEXT,
    "marked_by" TEXT NOT NULL,
    "marked_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "subject_attendance_records_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "subject_attendance_records_school_id_idx" ON "subject_attendance_records"("school_id");

-- CreateIndex
CREATE INDEX "subject_attendance_arm_subject_date_idx" ON "subject_attendance_records"("school_id", "class_arm_id", "subject_id", "date");

-- CreateIndex
CREATE INDEX "subject_attendance_arm_subject_term_idx" ON "subject_attendance_records"("school_id", "class_arm_id", "subject_id", "term_id");

-- CreateIndex
CREATE UNIQUE INDEX "subject_attendance_records_school_id_student_id_subject_id__key" ON "subject_attendance_records"("school_id", "student_id", "subject_id", "date", "period");

-- ---------------------------------------------------------------------
-- Slice 8 RLS policy (verbatim from prisma/policies/phase-2.sql). Own
-- school_id → flat direct-column check. FORCE so the migration role cannot
-- bypass at runtime. (No policy on schools — its Phase-0 policy already
-- covers the new column.)
-- ---------------------------------------------------------------------

ALTER TABLE "subject_attendance_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subject_attendance_records" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "subject_attendance_records"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
