-- Phase 1 / Slice 4 — Students (manual CRUD).
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma
-- --script`; RLS policy block appended verbatim from
-- packages/db/prisma/policies/phase-1.sql (the policy file is the
-- source of truth — keep these in sync).
--
-- date_of_birth is DATE (no time-of-day) because dateOfBirth is a
-- calendar date — see CLAUDE.md "Prisma column types in raw SQL" and
-- the slice-4 reconciliation note in docs/modules/phase-1.md. The
-- timestamps (admitted_at, withdrawn_at, graduated_at, created_at,
-- updated_at) stay as TIMESTAMP(3) because those are events, not
-- calendar dates.
--
-- SECURITY DEFINER count stays at 4. Every Student endpoint is
-- post-authentication and post-tenant; withTenant() covers all access.

-- CreateEnum
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');

-- CreateEnum
CREATE TYPE "StudentStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'WITHDRAWN', 'GRADUATED', 'SUSPENDED');

-- CreateTable
CREATE TABLE "students" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "admission_number" TEXT NOT NULL,
    "first_name" TEXT NOT NULL,
    "middle_name" TEXT,
    "last_name" TEXT NOT NULL,
    "date_of_birth" DATE NOT NULL,
    "gender" "Gender" NOT NULL,
    "photo_url" TEXT,
    "address" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "blood_group" TEXT,
    "medical_notes" TEXT,
    "religion" TEXT,
    "state_of_origin" TEXT,
    "nationality" TEXT NOT NULL DEFAULT 'Nigerian',
    "status" "StudentStatus" NOT NULL DEFAULT 'ACTIVE',
    "admitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawn_at" TIMESTAMP(3),
    "graduated_at" TIMESTAMP(3),
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "students_school_id_idx" ON "students"("school_id");

-- CreateIndex
CREATE INDEX "students_school_id_status_idx" ON "students"("school_id", "status");

-- CreateIndex
CREATE INDEX "students_school_id_last_name_first_name_idx" ON "students"("school_id", "last_name", "first_name");

-- CreateIndex
CREATE UNIQUE INDEX "students_school_id_admission_number_key" ON "students"("school_id", "admission_number");

-- ---------------------------------------------------------------------
-- Slice 4 RLS policy (verbatim from prisma/policies/phase-1.sql).
-- Same shape as every prior Phase 1 slice: ENABLE + FORCE on the table,
-- then a tenant_isolation policy with USING + WITH CHECK on the
-- denormalised school_id column. Defence-in-depth against a buggy
-- controller ever inserting a Student with a foreign school_id.
-- ---------------------------------------------------------------------

ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE students FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON students
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
