-- Phase 1 / Slice 12 — AI foundation tables (MasteryRecord + AIInteractionLog).
--
-- DDL generated by `prisma migrate diff --from-url $DIRECT_URL
-- --to-schema-datamodel ./prisma/schema.prisma --script` (live DB was at the
-- slice-11 migrated state). RLS policy block appended verbatim from
-- packages/db/prisma/policies/phase-1.sql (the policy file is the source of
-- truth — keep these in sync).
--
-- WHY THESE EXIST: lock in school_id + RLS shape NOW so Phase 5 fills EMPTY
-- tables instead of running a live-data migration on populated ones. They
-- SIT EMPTY in Phase 1 — this slice is a hard gate against premature
-- Phase-5 work, not a feature. Closes acceptance #13; contributes the last
-- two of the 15 Phase-1 tables to acceptance #10.
--
-- DELIBERATE OMISSIONS (Phase 5 owns these; adding them now would pre-empt a
-- decision docs/modules/phase-1.md intentionally punts):
--   - MasteryRecord: NO score column (0-1 vs 0-100 vs letter is Phase 5), NO
--     time-decay field beyond updated_at, NO source/origin column (tutor vs
--     assessment vs manual). status is free-text TEXT now (enum in Phase 5);
--     topic_ref is a loose TEXT id so the grain (subject/topic/objective)
--     can be chosen later without a migration.
--   - AIInteractionLog: payload is an OPAQUE JSONB envelope, structure owned
--     by Phase 5. It MUST stay PII-free per CLAUDE.md AI hard rules (never
--     send student PII to the LLM; log opaque ids + class-level context
--     only). The inline-vs-R2 storage tradeoff (cost/PII/eval) is a Phase-5
--     decision made when there is a real payload — not pre-built here.
--
-- NAMING DRIFT (reconcile in Phase 5, tracked in docs/deferred.md):
-- ARCHITECTURE.md §5/§7 and CLAUDE.md's AI hard rules name the LLM-call log
-- `AIGeneration`/`ai_generations`; this table is `AIInteractionLog`/
-- `ai_interaction_logs`. Phase 5 MUST rename/absorb one into the other (or
-- define the boundary) BEFORE building the claudeClient call-logger so we do
-- not end up with two overlapping tables.
--
-- Both tables carry their OWN school_id (despite the student_id FK) → flat
-- direct-column RLS, same cheap pattern as student_guardians (see
-- docs/modules/phase-1.md "Note on student_guardians"). No SECURITY DEFINER
-- function is added: there are no endpoints and no pre-tenant access. SECURITY
-- DEFINER count stays at 4.

-- CreateTable
CREATE TABLE "mastery_records" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "topic_ref" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mastery_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_interaction_logs" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT,
    "session_ref" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_interaction_logs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "mastery_records_school_id_idx" ON "mastery_records"("school_id");

-- CreateIndex
CREATE INDEX "mastery_records_student_id_idx" ON "mastery_records"("student_id");

-- CreateIndex
CREATE UNIQUE INDEX "mastery_records_school_id_student_id_topic_ref_key" ON "mastery_records"("school_id", "student_id", "topic_ref");

-- CreateIndex
CREATE INDEX "ai_interaction_logs_school_id_idx" ON "ai_interaction_logs"("school_id");

-- CreateIndex
CREATE INDEX "ai_interaction_logs_school_id_created_at_idx" ON "ai_interaction_logs"("school_id", "created_at");

-- CreateIndex
CREATE INDEX "ai_interaction_logs_student_id_idx" ON "ai_interaction_logs"("student_id");

-- AddForeignKey
ALTER TABLE "mastery_records" ADD CONSTRAINT "mastery_records_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_interaction_logs" ADD CONSTRAINT "ai_interaction_logs_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 12 RLS policies (verbatim from prisma/policies/phase-1.sql).
-- Both tables carry their own school_id → flat direct-column check, NOT
-- EXISTS-through-students (docs/modules/phase-1.md "Note on
-- student_guardians"). FORCE so the migration role cannot bypass.
-- ---------------------------------------------------------------------

ALTER TABLE "mastery_records"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mastery_records"     FORCE  ROW LEVEL SECURITY;
ALTER TABLE "ai_interaction_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_interaction_logs" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "mastery_records"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON "ai_interaction_logs"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
