-- Phase 1 / Slice 10 — TeacherProfile + minimal teacher role seed.
--
-- DDL generated by `prisma migrate diff --from-url $DIRECT_URL
-- --to-schema-datamodel ./prisma/schema.prisma --script` (live DB was at
-- the slice-9 migrated state). RLS policy block appended verbatim from
-- packages/db/prisma/policies/phase-1.sql (the policy file is the source
-- of truth — keep these in sync).
--
-- TeacherProfile is the 1:1 HR record for a teacher-role User. It is
-- created EXPLICITLY by an admin after the teacher accepts their
-- invitation (Q2 lifecycle locked 2026-05-30) — the invitation-accept
-- path is untouched, so no SECURITY DEFINER function is added here.
-- SECURITY DEFINER count stays at 4.
--
-- Two unique constraints: user_id (1:1) and (school_id, staff_number).
-- The service pre-checks both before insert so it can return precise 409
-- codes; under FORCE RLS the P2002 constraint name is stripped.
--
-- The minimal `teacher` SYSTEM ROLE is seeded at the bottom of THIS
-- migration (not a manual `db:seed` step) so existing + CI databases that
-- run `migrate deploy` get it automatically. Without it, invitation-accept
-- of a teacher rolls back ("System role 'teacher' is not seeded") and
-- class-arms' assertUserIsTeacher always fails — the whole staff branch is
-- untestable. This carries only the read-scoped permissions per
-- phase-1.md:1087; the full RBAC rollup + existing-school role migration
-- stays slice 13. The insert is idempotent (WHERE NOT EXISTS) and is kept
-- in sync with packages/db/prisma/seed-data.ts (the canonical fresh-seed
-- source), which also lists the `teacher` role.

-- CreateTable
CREATE TABLE "teacher_profiles" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "staff_number" TEXT NOT NULL,
    "qualifications" TEXT,
    "specialty" TEXT,
    "nut_number" TEXT,
    "joined_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "teacher_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "teacher_profiles_user_id_key" ON "teacher_profiles"("user_id");

-- CreateIndex
CREATE INDEX "teacher_profiles_school_id_idx" ON "teacher_profiles"("school_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_profiles_school_id_staff_number_key" ON "teacher_profiles"("school_id", "staff_number");

-- AddForeignKey
ALTER TABLE "teacher_profiles" ADD CONSTRAINT "teacher_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 10 RLS policy (verbatim from prisma/policies/phase-1.sql).
-- Direct school_id column; FORCE so the migration role cannot bypass it.
-- ---------------------------------------------------------------------

ALTER TABLE "teacher_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teacher_profiles" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "teacher_profiles"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

-- ---------------------------------------------------------------------
-- Minimal `teacher` system role seed (school_id IS NULL, is_system).
-- Idempotent: roles(school_id, key) treats NULL school_id as DISTINCT in
-- Postgres, so ON CONFLICT cannot dedupe a NULL-school row — we guard with
-- WHERE NOT EXISTS instead. id is generated here (the Prisma model uses a
-- client-side @default(uuid()), so the column has no DB default).
-- Permissions = the read-scoped subset from phase-1.md:1087; kept in sync
-- with seed-data.ts. Full rollup is slice 13.
-- ---------------------------------------------------------------------

INSERT INTO "roles" ("id", "school_id", "key", "name", "description", "is_system", "permissions", "created_at")
SELECT
    gen_random_uuid()::text,
    NULL,
    'teacher',
    'Teacher',
    'Teaching staff — read-scoped access to their assigned arms, subjects, and roster, plus self-service on their own profile. Full RBAC rollup lands in slice 13.',
    true,
    '["class-arm.read","class-level.read","subject.read","class-subject.read","teacher-assignment.read","teacher-profile.self.read","teacher-profile.self.update","student.read","enrollment.read"]'::jsonb,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM "roles"
    WHERE "school_id" IS NULL AND "key" = 'teacher' AND "is_system" = true
);
