-- Phase 1 / Slice 1 — Academic structure (year + term).
-- DDL generated by `prisma migrate diff`; RLS policies + partial unique
-- indexes appended verbatim from packages/db/prisma/policies/phase-1.sql
-- (the policy file is the source of truth — keep these in sync).

-- CreateTable
CREATE TABLE "academic_years" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "is_current" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "academic_years_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "terms" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "is_current" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "terms_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "academic_years_school_id_idx" ON "academic_years"("school_id");

-- CreateIndex
CREATE INDEX "academic_years_school_id_is_current_idx" ON "academic_years"("school_id", "is_current");

-- CreateIndex
CREATE UNIQUE INDEX "academic_years_school_id_label_key" ON "academic_years"("school_id", "label");

-- CreateIndex
CREATE INDEX "terms_school_id_idx" ON "terms"("school_id");

-- CreateIndex
CREATE INDEX "terms_school_id_is_current_idx" ON "terms"("school_id", "is_current");

-- CreateIndex
CREATE UNIQUE INDEX "terms_academic_year_id_sequence_key" ON "terms"("academic_year_id", "sequence");

-- AddForeignKey
ALTER TABLE "terms" ADD CONSTRAINT "terms_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Phase 1 RLS policies (verbatim from prisma/policies/phase-1.sql).
-- Same shape as phase-0.sql: ENABLE + FORCE on each table, then a
-- tenant_isolation policy with USING + WITH CHECK.
-- ---------------------------------------------------------------------

ALTER TABLE academic_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic_years FORCE  ROW LEVEL SECURITY;
ALTER TABLE terms          ENABLE ROW LEVEL SECURITY;
ALTER TABLE terms          FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON academic_years
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON terms
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

-- Partial unique indexes — "exactly one current per school". The service
-- layer flips siblings to false BEFORE flipping the target, in one
-- transaction; the partial index is the correct-by-construction guard.

CREATE UNIQUE INDEX academic_years_school_id_current_key
  ON academic_years (school_id)
  WHERE is_current = true;

CREATE UNIQUE INDEX terms_school_id_current_key
  ON terms (school_id)
  WHERE is_current = true;
