import { z } from "zod";

// Weekly parent progress summary — Phase 5 / Slice 5.
//
// The unit is (student, week). One note per child per week, generated by a
// cron sweep and read by their guardian in the portal.
//
// NOTE WHAT IS ABSENT HERE, because it is the difference between this slice
// and every other AI slice in the phase: there is no accept DTO, no
// suggestion field, and no editable flag. Slices 3-4 model a draft a teacher
// approves; this models a delivered artifact (phase-5.md D16). The school's
// opt-in is the control, so the only write DTO in this file is the one that
// flips that switch.

// ---------------------------------------------------------------------------
// Portal surface (guardian-facing)
// ---------------------------------------------------------------------------

// GET /portal/students/:id/summaries
//
// Carries no child name and no school name: the portal page that renders
// this already holds both, and the guardian is looking at one child's page.
// Re-sending identity onto an AI-generated surface would widen the PII
// footprint for no benefit — same reasoning as FormCommentRowDto.
export interface PortalParentSummaryDto {
  id: string;
  // Monday of the covered week (DATE, no time-of-day). The client formats a
  // range from this; the API does not send a pre-formatted label, so the
  // portal can localise it later without an API change.
  weekStart: string | Date;
  summary: string;
}

export interface PortalParentSummaryListResponse {
  data: PortalParentSummaryDto[];
}

// ---------------------------------------------------------------------------
// Staff surface (school-facing)
// ---------------------------------------------------------------------------

// GET /parent-summaries?studentId=&limit=
//
// What the school can see of what was sent to parents. `studentId` is
// optional: a form teacher looking into one complaint filters by child, an
// admin auditing the feature after switching it on reads the most recent
// notes across the school.
export const listParentSummariesSchema = z
  .object({
    studentId: z.string().uuid().optional(),
    limit: z.coerce.number().int().min(1).max(100).default(20),
  })
  .strict();

export type ListParentSummariesInput = z.infer<typeof listParentSummariesSchema>;

// The staff view DOES carry studentId — unlike the portal view, the reader
// here is looking across children and needs to know whose note this is.
export interface ParentSummaryRowDto {
  id: string;
  studentId: string;
  weekStart: string | Date;
  summary: string;
  // Null means generated but not emailed: notifications off, no guardian
  // email on file, or a failed send. All ordinary states — the portal shows
  // the note either way, so this is "was it pushed to them" not "can they
  // see it".
  emailedAt: string | Date | null;
  promptVersion: string;
  createdAt: string | Date;
}

// PATCH /parent-summaries/settings — the D16 opt-in switch.
//
// A dedicated endpoint rather than a field on the general school-settings
// update, deliberately: this is the switch that decides whether unattended
// AI output reaches parents, it is gated on its own permission
// (`parent-summary.manage`, admin/owner only), and it writes an audit row.
// Burying it in a PATCH /schools/me body would make all three easy to lose.
export const updateParentSummarySettingsSchema = z
  .object({
    enabled: z.boolean(),
  })
  .strict();

export type UpdateParentSummarySettingsInput = z.infer<
  typeof updateParentSummarySettingsSchema
>;

export interface ParentSummarySettingsDto {
  enabled: boolean;
  // Surfaced so the settings screen can explain *why* the feature is inert
  // when it is: a school can have the switch on while AI itself is disabled
  // school-wide, or unconfigured platform-wide. Three different states that
  // otherwise look identical from the UI ("it's on but nothing arrives").
  aiEnabled: boolean;
  aiConfigured: boolean;
}
