-- Phase 2 / Slice 1 — Grading configuration (GradingScheme + GradingComponent
-- + GradeBoundary).
--
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma --script`
-- (live DB was at the Phase-1 slice-13 migrated state). RLS policy block
-- appended verbatim from packages/db/prisma/policies/phase-2.sql (the policy
-- file is the source of truth — keep these in sync). A one-time idempotent
-- BACKFILL block follows the RLS block.
--
-- Three per-school config tables, all carrying their OWN school_id → flat
-- direct-column RLS (the same cheap pattern as every Phase 1 table). New
-- schools are seeded inside signupOwner (same tx as the class-level seed);
-- EXISTING schools are seeded by the backfill below.
--
-- SECURITY DEFINER count stays at 4: every grading endpoint is post-auth and
-- post-tenant (withTenant covers all runtime access); the signup seed rides the
-- existing tx's GUC; the backfill runs as the migration role. CLAUDE.md
-- inventory is unchanged.

-- CreateTable
CREATE TABLE "grading_schemes" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "grading_schemes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "grading_components" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "scheme_id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "weight" INTEGER NOT NULL,
    "order_index" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "grading_components_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "grade_boundaries" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "letter" TEXT NOT NULL,
    "min_score" INTEGER NOT NULL,
    "max_score" INTEGER NOT NULL,
    "remark" TEXT,
    "order_index" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "grade_boundaries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "grading_schemes_school_id_key" ON "grading_schemes"("school_id");

-- CreateIndex
CREATE INDEX "grading_components_school_id_idx" ON "grading_components"("school_id");

-- CreateIndex
CREATE UNIQUE INDEX "grading_components_school_id_scheme_id_key_key" ON "grading_components"("school_id", "scheme_id", "key");

-- CreateIndex
CREATE INDEX "grade_boundaries_school_id_idx" ON "grade_boundaries"("school_id");

-- CreateIndex
CREATE UNIQUE INDEX "grade_boundaries_school_id_letter_key" ON "grade_boundaries"("school_id", "letter");

-- AddForeignKey
ALTER TABLE "grading_components" ADD CONSTRAINT "grading_components_scheme_id_fkey" FOREIGN KEY ("scheme_id") REFERENCES "grading_schemes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 1 RLS policies (verbatim from prisma/policies/phase-2.sql).
-- All three tables carry their own school_id → flat direct-column check.
-- FORCE so the migration role cannot bypass at runtime.
-- ---------------------------------------------------------------------

ALTER TABLE "grading_schemes"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "grading_schemes"    FORCE  ROW LEVEL SECURITY;
ALTER TABLE "grading_components" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "grading_components" FORCE  ROW LEVEL SECURITY;
ALTER TABLE "grade_boundaries"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "grade_boundaries"   FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "grading_schemes"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON "grading_components"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON "grade_boundaries"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

-- ---------------------------------------------------------------------
-- One-time BACKFILL for schools created BEFORE this slice (they have no
-- grading config; Phase 2 / Slice 2 scores depend on a scheme existing).
--
-- Runs as the migration role (school_kit, a SUPERUSER) which BYPASSES RLS
-- (CLAUDE.md "Postgres silently skips RLS for privileged roles") — so these
-- cross-school INSERTs need no app.current_school_id GUC. gen_random_uuid()
-- is Postgres-16 core (no extension required) and matches Prisma's text uuid
-- id shape via ::text.
--
-- Idempotent: every INSERT is guarded by NOT EXISTS, so a re-run of
-- `migrate deploy` (or a deploy after a partial failure) is a no-op. New
-- schools never reach the backfill — signupOwner seeds them first, so the
-- guards short-circuit.
--
-- KEEP IN SYNC with packages/db/src/seeds/grading.ts (DEFAULT_GRADING_*). The
-- VALUES lists below are the SQL mirror of those constants. If you change a
-- default there, change it here too (mismatch would make backfilled schools
-- differ from freshly-signed-up ones).
-- ---------------------------------------------------------------------

-- 1. One scheme per schemeless school.
INSERT INTO "grading_schemes" ("id", "school_id", "name", "is_active", "created_at", "updated_at")
SELECT gen_random_uuid()::text, s."id", 'WAEC-style (default)', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "schools" s
WHERE NOT EXISTS (
  SELECT 1 FROM "grading_schemes" gs WHERE gs."school_id" = s."id"
);

-- 2. The three default components for any scheme that has none (covers the
--    schemes just created above; the NOT EXISTS keeps it idempotent).
INSERT INTO "grading_components" ("id", "school_id", "scheme_id", "key", "label", "weight", "order_index", "created_at", "updated_at")
SELECT gen_random_uuid()::text, gs."school_id", gs."id", c."key", c."label", c."weight", c."order_index", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "grading_schemes" gs
CROSS JOIN (VALUES
  ('ca1',  'First CA',  20, 1),
  ('ca2',  'Second CA', 20, 2),
  ('exam', 'Exam',      60, 3)
) AS c("key", "label", "weight", "order_index")
WHERE NOT EXISTS (
  SELECT 1 FROM "grading_components" gc WHERE gc."scheme_id" = gs."id"
);

-- 3. The nine WAEC bands for any school that has none.
INSERT INTO "grade_boundaries" ("id", "school_id", "letter", "min_score", "max_score", "remark", "order_index", "created_at", "updated_at")
SELECT gen_random_uuid()::text, s."id", b."letter", b."min_score", b."max_score", b."remark", b."order_index", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM "schools" s
CROSS JOIN (VALUES
  ('A1', 75, 100, 'Excellent', 1),
  ('B2', 70, 74,  'Very Good', 2),
  ('B3', 65, 69,  'Good',      3),
  ('C4', 60, 64,  'Credit',    4),
  ('C5', 55, 59,  'Credit',    5),
  ('C6', 50, 54,  'Credit',    6),
  ('D7', 45, 49,  'Pass',      7),
  ('E8', 40, 44,  'Pass',      8),
  ('F9', 0,  39,  'Fail',      9)
) AS b("letter", "min_score", "max_score", "remark", "order_index")
WHERE NOT EXISTS (
  SELECT 1 FROM "grade_boundaries" gb WHERE gb."school_id" = s."id"
);
