-- Phase 2 / Slice 2 — Assessment + AssessmentScore.
--
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma --script`
-- (live DB was at the Phase-2 slice-1 migrated state). RLS policy block appended
-- verbatim from packages/db/prisma/policies/phase-2.sql (the policy file is the
-- source of truth — keep these in sync).
--
-- AssessmentScore is the raw mark a teacher types (score ∈ [0, component.weight],
-- enforced in the service against the LIVE component row). Assessment is the
-- denormalized per-(student × subject × term) summary, materialized in the SAME
-- tx as the score write (phase-2.md "Grades are computed server-side"). Both
-- carry their own school_id → flat direct-column RLS. The score's only enforced
-- relation is to grading_components (ON DELETE RESTRICT — we need its live weight
-- to validate, and a component with entered scores must not vanish).
--
-- SECURITY DEFINER count stays at 4: every endpoint (cp2/cp3) is post-auth and
-- post-tenant; withTenant covers all access. CLAUDE.md inventory unchanged.

-- CreateTable
CREATE TABLE "assessment_scores" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "component_id" TEXT NOT NULL,
    "score" INTEGER NOT NULL,
    "entered_by" TEXT NOT NULL,
    "entered_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "assessment_scores_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "assessments" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "total_score" INTEGER NOT NULL,
    "letter_grade" TEXT,
    "remark" TEXT,
    "subject_position" INTEGER,
    "class_position" INTEGER,
    "subject_comment" TEXT,
    "subject_signed_off_at" TIMESTAMP(3),
    "subject_signed_off_by" TEXT,
    "computed_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "assessments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "assessment_scores_school_id_idx" ON "assessment_scores"("school_id");

-- CreateIndex
CREATE INDEX "assessment_scores_school_id_term_id_subject_id_idx" ON "assessment_scores"("school_id", "term_id", "subject_id");

-- CreateIndex
CREATE UNIQUE INDEX "assessment_scores_school_id_student_id_subject_id_term_id_c_key" ON "assessment_scores"("school_id", "student_id", "subject_id", "term_id", "component_id");

-- CreateIndex
CREATE INDEX "assessments_school_id_idx" ON "assessments"("school_id");

-- CreateIndex
CREATE INDEX "assessments_school_id_term_id_subject_id_class_arm_id_idx" ON "assessments"("school_id", "term_id", "subject_id", "class_arm_id");

-- CreateIndex
CREATE INDEX "assessments_school_id_class_arm_id_term_id_idx" ON "assessments"("school_id", "class_arm_id", "term_id");

-- CreateIndex
CREATE UNIQUE INDEX "assessments_school_id_student_id_subject_id_term_id_key" ON "assessments"("school_id", "student_id", "subject_id", "term_id");

-- AddForeignKey
ALTER TABLE "assessment_scores" ADD CONSTRAINT "assessment_scores_component_id_fkey" FOREIGN KEY ("component_id") REFERENCES "grading_components"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 2 RLS policies (verbatim from prisma/policies/phase-2.sql).
-- Both tables carry their own school_id → flat direct-column check, NOT
-- EXISTS-through-component. FORCE so the migration role cannot bypass.
-- ---------------------------------------------------------------------

ALTER TABLE "assessment_scores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessment_scores" FORCE  ROW LEVEL SECURITY;
ALTER TABLE "assessments"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessments"       FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "assessment_scores"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));

CREATE POLICY tenant_isolation ON "assessments"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
