-- Phase 2 / Slice 5 — Report card (the 8th and final Phase 2 table).
--
-- DDL generated by `prisma migrate diff --from-schema-datasource
-- ./prisma/schema.prisma --to-schema-datamodel ./prisma/schema.prisma --script`
-- (live DB at the Phase-2 slice-4 migrated state). RLS policy block appended
-- verbatim from packages/db/prisma/policies/phase-2.sql (source of truth).
--
-- Materialized per-(student × term) artifact: the term rollup (snapshotted at
-- BUILD so the PDF reads a frozen rollup), the workflow state (slice 6 drives
-- the machine; slice 5 only creates DRAFT), the three comment grains, and the
-- R2 PDF pointer (slice 5 cp2). Own school_id → flat direct-column RLS.
--
-- SECURITY DEFINER count stays at 4: every endpoint is post-auth and
-- post-tenant (withTenant); the render worker establishes tenant context via
-- tenantWorker. CLAUDE.md inventory unchanged.

-- CreateEnum
CREATE TYPE "ReportCardStatus" AS ENUM ('DRAFT', 'SUBJECT_REVIEWED', 'FORM_REVIEWED', 'PRINCIPAL_APPROVED', 'RELEASED');

-- CreateEnum
CREATE TYPE "ReportCardPdfStatus" AS ENUM ('PENDING', 'GENERATING', 'GENERATED', 'FAILED');

-- CreateTable
CREATE TABLE "report_cards" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "status" "ReportCardStatus" NOT NULL DEFAULT 'DRAFT',
    "overall_total" INTEGER,
    "overall_average" INTEGER,
    "overall_position" INTEGER,
    "subjects_count" INTEGER,
    "form_teacher_comment" TEXT,
    "principal_note" TEXT,
    "form_reviewed_at" TIMESTAMP(3),
    "form_reviewed_by" TEXT,
    "principal_approved_at" TIMESTAMP(3),
    "principal_approved_by" TEXT,
    "released_at" TIMESTAMP(3),
    "pdf_status" "ReportCardPdfStatus" NOT NULL DEFAULT 'PENDING',
    "artifact_url" TEXT,
    "generated_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "report_cards_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "report_cards_school_id_idx" ON "report_cards"("school_id");

-- CreateIndex
CREATE INDEX "report_cards_school_id_class_arm_id_term_id_status_idx" ON "report_cards"("school_id", "class_arm_id", "term_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "report_cards_school_id_student_id_term_id_key" ON "report_cards"("school_id", "student_id", "term_id");

-- ---------------------------------------------------------------------
-- Slice 5 RLS policy (verbatim from prisma/policies/phase-2.sql). Own
-- school_id → flat direct-column check. FORCE so the migration role cannot
-- bypass at runtime.
-- ---------------------------------------------------------------------

ALTER TABLE "report_cards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "report_cards" FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON "report_cards"
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
