-- Phase 1 / Slice 9 — Enrollment (per-term).
-- DDL generated by `prisma migrate diff --from-migrations ... --to-schema-
-- datamodel ./prisma/schema.prisma --script`; RLS policy block appended
-- verbatim from packages/db/prisma/policies/phase-1.sql (the policy file
-- is the source of truth — keep these in sync).
--
-- One row per (school, student, term). The @@unique below enforces
-- "no two enrollments for the same student in the same term". Withdraw
-- + re-enroll same term flips status in place; the WITHDRAWN row is not
-- preserved at the table level (audit_logs holds the trail).
--
-- academic_year_id is denormalised from term.academic_year_id for cheap
-- "all students enrolled in 2025/2026" queries. The service layer
-- resolves it from termId at write time; the API never accepts it from
-- a request body. Phase 1 keeps the columns consistent as a service-
-- layer invariant (a CHECK constraint or trigger could enforce it at
-- the DB layer in Phase 2 — currently captured in docs/deferred.md).
--
-- All four FKs use ON DELETE CASCADE: deleting a Student, Term,
-- AcademicYear, or ClassArm cascades to its enrollments. In practice
-- the service rejects parent deletes that would orphan enrollments
-- (see the AcademicYear / Term / ClassArm delete guards from slices 1
-- and 3); the cascade is belt-and-braces against a hand-run SQL
-- DELETE.
--
-- SECURITY DEFINER count stays at 4. Every enrollment endpoint is
-- post-authentication and post-tenant; withTenant() covers all access.

-- CreateEnum
CREATE TYPE "EnrollmentStatus" AS ENUM ('ENROLLED', 'TRANSFERRED', 'PROMOTED', 'REPEATED', 'WITHDRAWN', 'GRADUATED');

-- CreateTable
CREATE TABLE "enrollments" (
    "id" TEXT NOT NULL,
    "school_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "term_id" TEXT NOT NULL,
    "academic_year_id" TEXT NOT NULL,
    "class_arm_id" TEXT NOT NULL,
    "status" "EnrollmentStatus" NOT NULL DEFAULT 'ENROLLED',
    "enrolled_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transferred_at" TIMESTAMP(3),
    "withdrawn_at" TIMESTAMP(3),
    "promoted_from_arm_id" TEXT,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "enrollments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "enrollments_school_id_idx" ON "enrollments"("school_id");

-- CreateIndex
CREATE INDEX "enrollments_class_arm_id_idx" ON "enrollments"("class_arm_id");

-- CreateIndex
CREATE INDEX "enrollments_school_id_term_id_idx" ON "enrollments"("school_id", "term_id");

-- CreateIndex
CREATE INDEX "enrollments_school_id_academic_year_id_idx" ON "enrollments"("school_id", "academic_year_id");

-- CreateIndex
CREATE UNIQUE INDEX "enrollments_school_id_student_id_term_id_key" ON "enrollments"("school_id", "student_id", "term_id");

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "terms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_class_arm_id_fkey" FOREIGN KEY ("class_arm_id") REFERENCES "class_arms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- Slice 9 RLS policy (verbatim from prisma/policies/phase-1.sql).
-- Same shape as every prior Phase 1 slice: ENABLE + FORCE on the table,
-- then a tenant_isolation policy with USING + WITH CHECK on the
-- denormalised school_id column. The CHECK side prevents a buggy
-- controller from ever inserting an Enrollment with a foreign school_id.
-- ---------------------------------------------------------------------

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON enrollments
  USING      (school_id::text = current_setting('app.current_school_id', true))
  WITH CHECK (school_id::text = current_setting('app.current_school_id', true));
